// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package provider

import (
	"todo-api/application/usecase"
)

// Injectors from wire.go:

func InitializeCreateTodoUseCase() *usecase.CreateTodoUseCase {
	todoRepository := NewTodoRepository()
	createTodoUseCase := usecase.NewCreateTodoUseCase(todoRepository)
	return createTodoUseCase
}

func InitializeFetchAllTodosUseCase() *usecase.FetchAllTodosUseCase {
	todoRepository := NewTodoRepository()
	fetchAllTodosUseCase := usecase.NewFetchAllTodosUseCase(todoRepository)
	return fetchAllTodosUseCase
}
