// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package provider

import (
	"todo-api/application/usecase/todo"
)

// Injectors from wire.go:

func InitializeCreateTodoUseCase() *todo.CreateTodoUseCase {
	todoRepository := NewTodoRepository()
	createTodoUseCase := todo.NewCreateTodoUseCase(todoRepository)
	return createTodoUseCase
}

func InitializeFetchAllTodosUseCase() *todo.FetchAllTodosUseCase {
	todoRepository := NewTodoRepository()
	fetchAllTodosUseCase := todo.NewFetchAllTodosUseCase(todoRepository)
	return fetchAllTodosUseCase
}
